data:
  motion_yaml: scripts/rsl_rl/motion_file_mr.yaml
  files: []
  dirs: [] 
  exclude_files: []
  exclude_dirs: []
  groups: []

features:
  robot_anchor_body: torso_link
  robot_body_names:
    - pelvis
    - left_hip_yaw_link
    - left_knee_link
    - left_ankle_roll_link
    - right_hip_yaw_link
    - right_knee_link
    - right_ankle_roll_link
    - torso_link
    - left_shoulder_pitch_link
    - left_shoulder_yaw_link
    - left_elbow_link
    - left_wrist_yaw_link
    - right_shoulder_pitch_link
    - right_shoulder_yaw_link
    - right_elbow_link
    - right_wrist_yaw_link
  robot_joint_names:
    - left_hip_pitch_joint
    - left_hip_roll_joint
    - left_hip_yaw_joint
    - left_knee_joint
    - left_ankle_pitch_joint
    - left_ankle_roll_joint
    - right_hip_pitch_joint
    - right_hip_roll_joint
    - right_hip_yaw_joint
    - right_knee_joint
    - right_ankle_pitch_joint
    - right_ankle_roll_joint
    - waist_yaw_joint
    - waist_roll_joint
    - waist_pitch_joint
    - left_shoulder_pitch_joint
    - left_shoulder_roll_joint
    - left_shoulder_yaw_joint
    - left_elbow_joint
    - left_wrist_roll_joint
    - left_wrist_pitch_joint
    - left_wrist_yaw_joint
    - right_shoulder_pitch_joint
    - right_shoulder_roll_joint
    - right_shoulder_yaw_joint
    - right_elbow_joint
    - right_wrist_roll_joint
    - right_wrist_pitch_joint
    - right_wrist_yaw_joint
  desire_human_joint_names:
    - Hips
    - Spine1
    - Spine2
    - Chest
    - Neck1
    - Neck2
    - Head
    - HeadEnd
    - LeftShoulder
    - LeftArm
    - LeftForeArm
    - LeftHand
    - RightShoulder
    - RightArm
    - RightForeArm
    - RightHand
    - LeftLeg
    - LeftShin
    - LeftFoot
    - LeftToeBase
    - LeftToeEnd
    - RightLeg
    - RightShin
    - RightFoot
    - RightToeBase
    - RightToeEnd
  human_anchor_body: Hips
  human_body_names:
    - Chest
    - HeadEnd
    - LeftShoulder
    - LeftArm
    - LeftForeArm
    - RightShoulder
    - RightArm
    - RightForeArm
    - LeftLeg
    - LeftShin
    - LeftFoot
    - RightLeg
    - RightShin
    - RightFoot

model:
  latent_dim: 128
  robot_encoder_hidden_dims: [1024, 512, 256]
  human_encoder_hidden_dims: [1024, 512, 256]
  decoder_hidden_dims: [256, 512, 1024]
  activation: silu
  quantizer:
    type: ifsq
    levels: 32
    ifsq_boundary_fn: sigmoid
    ifsq_boundary_scale: 1.6

loss:
  robot_recon: 1.0
  human_recon: 1.0
  latent_align: 2.5
  cycle_latent: 0.25

train:
  device: cuda
  epochs: 10000
  batch_size: 98304
  learning_rate: 0.0003
  weight_decay: 0.0001
  history: 0
  future: 9
  seed: 1
  log_every_steps: 20
  checkpoint_interval_epochs: 10
  normalizer_eps: 0.01
  progress: true

output:
  root_dir: outputs/motion_fsq_reconstruction
  run_name:
